### ISSUE TITLE
Radical #143 (虫) has incorrect audio

### ISSUE THREAD

**Issue by slodyssey** [jay-pee/Anki-Chinese-Radicals-Deck-Plus#2]
Seems like this audio for this card is off - it sounds like hui, but should be chóng

**Comment by slodyssey** [comment]
I confirmed the card for 虫 generated with the sound file cmn-hui3.mp3, and moreover, that there is no chong.mp3 file in the anki media folder

**Comment by jay-pee** [comment]
fixed

https://github.com/jay-pee/Anki-Chinese-Radicals-Deck-Plus/blame/070e56fc99abc12d27e188fd0daddebea3d9dfae/data/source_examples.csv#L142
