### ISSUE TITLE
Radical 118 竹: cmn-zhu2 might have incorrect audio

### ISSUE THREAD

**Issue by slodyssey** [jay-pee/Anki-Chinese-Radicals-Deck-Plus#4]
It's a little hard to make out, but this audio sounds really really close to bu2. Could just be a minimal pair, but in the [zdic](https://www.zdic.net/hans/%E7%AB%B9) audio the initial very clearly sounds like **zh** and not **b**.

After some more digging, if there's an error it appears to be in the Audio-cmn project's recordings. I've opened an issue [there](https://github.com/hugolpz/audio-cmn/issues/10), but if the audio is incorrect, I guess this is an open issue for this project as long as it's not fixed upstream at Audio-cmn.

**Comment by jay-pee** [comment]
Should be fixed now

https://github.com/jay-pee/Anki-Chinese-Radicals-Deck-Plus/blame/070e56fc99abc12d27e188fd0daddebea3d9dfae/data/source_examples.csv#L118
